# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

VOLUME /data

EXPOSE 9410
# Install the required packages
RUN pip install --no-cache-dir sentence_transformers bson requests ray

# Run the Python script when the container launches
CMD ["python", "ray_serve.py"]

HEALTHCHECK CMD curl --fail http://localhost:5000 || exit 1